[project]
name = "honduras"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.10.0",
    "marimo>=0.19.7",
    "polars[all]>=1.37.1",
    "unicode>=2.9",
    "unidecode>=1.4.0",
]
